begin;

create extension if not exists citext;

create type public.social_intent as enum (
  'talk',
  'meet',
  'deep_conversation',
  'create',
  'debate',
  'listen',
  'hang_out'
);

create type public.room_status as enum ('open', 'closed', 'archived');
create type public.connection_status as enum ('pending', 'accepted', 'blocked');
create type public.age_status as enum ('self_attested', 'verified');
create type public.ledger_direction as enum ('debit', 'credit');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  handle citext unique,
  display_name text,
  bio text not null default '',
  avatar_url text,
  current_intent public.social_intent not null default 'talk',
  interests text[] not null default '{}',
  onboarding_completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_handle_format check (handle is null or handle::text ~ '^[a-z0-9_]{3,24}$'),
  constraint profiles_display_name_length check (display_name is null or char_length(display_name) <= 60),
  constraint profiles_bio_length check (char_length(bio) <= 500),
  constraint profiles_interests_limit check (cardinality(interests) <= 12)
);

create table public.user_private (
  id uuid primary key references auth.users(id) on delete cascade,
  date_of_birth date not null,
  age_status public.age_status not null default 'self_attested',
  age_verified_at timestamptz,
  terms_accepted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint adult_only check (date_of_birth <= (current_date - interval '18 years')::date)
);

create table public.rooms (
  id uuid primary key default gen_random_uuid(),
  created_by uuid not null references public.profiles(id) on delete restrict,
  title text not null,
  description text not null default '',
  current_intent public.social_intent not null default 'talk',
  max_participants smallint not null default 8,
  status public.room_status not null default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint room_title_length check (char_length(title) between 3 and 100),
  constraint room_capacity check (max_participants between 2 and 24)
);

create table public.room_members (
  room_id uuid not null references public.rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  left_at timestamptz,
  primary key (room_id, user_id)
);

create table public.messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  edited_at timestamptz,
  constraint message_length check (char_length(body) between 1 and 4000)
);

create table public.connections (
  requester_id uuid not null references public.profiles(id) on delete cascade,
  addressee_id uuid not null references public.profiles(id) on delete cascade,
  status public.connection_status not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (requester_id, addressee_id),
  constraint no_self_connection check (requester_id <> addressee_id)
);

create table public.wallet_links (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  chain_id bigint not null,
  address citext not null,
  wallet_type text not null default 'base_account',
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  unique (chain_id, address),
  unique (user_id, chain_id, address)
);

create table public.ledger_accounts (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid references public.profiles(id) on delete restrict,
  code text unique not null,
  asset text not null default 'USDC',
  account_type text not null,
  created_at timestamptz not null default now()
);

create table public.ledger_entries (
  id uuid primary key default gen_random_uuid(),
  idempotency_key text unique not null,
  reference_type text not null,
  reference_id text,
  external_tx_hash text,
  created_at timestamptz not null default now()
);

create table public.ledger_postings (
  id bigint generated by default as identity primary key,
  entry_id uuid not null references public.ledger_entries(id) on delete restrict,
  account_id uuid not null references public.ledger_accounts(id) on delete restrict,
  direction public.ledger_direction not null,
  amount_minor numeric(78,0) not null,
  created_at timestamptz not null default now(),
  constraint posting_amount_positive check (amount_minor > 0)
);

create index messages_room_created_idx on public.messages(room_id, created_at);
create index room_members_user_idx on public.room_members(user_id, left_at);
create index profiles_intent_idx on public.profiles(current_intent) where onboarding_completed_at is not null;
create index rooms_status_intent_idx on public.rooms(status, current_intent);
create index ledger_postings_entry_idx on public.ledger_postings(entry_id);
create index ledger_accounts_owner_idx on public.ledger_accounts(owner_user_id);

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_updated_at before update on public.profiles
for each row execute procedure public.set_updated_at();
create trigger user_private_updated_at before update on public.user_private
for each row execute procedure public.set_updated_at();
create trigger rooms_updated_at before update on public.rooms
for each row execute procedure public.set_updated_at();
create trigger connections_updated_at before update on public.connections
for each row execute procedure public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  dob date;
begin
  dob := nullif(new.raw_user_meta_data->>'date_of_birth', '')::date;

  if dob is null or dob > (current_date - interval '18 years')::date then
    raise exception 'Ponder+ requires an adult date of birth';
  end if;

  insert into public.profiles (id, display_name)
  values (new.id, nullif(new.raw_user_meta_data->>'display_name', ''));

  insert into public.user_private (id, date_of_birth, age_status)
  values (new.id, dob, 'self_attested');

  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.assert_balanced_ledger_entry()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  target_entry uuid;
  debits numeric(78,0);
  credits numeric(78,0);
begin
  if tg_op = 'DELETE' then
    target_entry := old.entry_id;
  else
    target_entry := new.entry_id;
  end if;

  select
    coalesce(sum(amount_minor) filter (where direction = 'debit'), 0),
    coalesce(sum(amount_minor) filter (where direction = 'credit'), 0)
  into debits, credits
  from public.ledger_postings
  where entry_id = target_entry;

  if debits <> credits then
    raise exception 'Unbalanced ledger entry %: debit %, credit %', target_entry, debits, credits;
  end if;

  return null;
end;
$$;

create constraint trigger ledger_entry_balanced
after insert or update or delete on public.ledger_postings
deferrable initially deferred
for each row execute procedure public.assert_balanced_ledger_entry();

alter table public.profiles enable row level security;
alter table public.user_private enable row level security;
alter table public.rooms enable row level security;
alter table public.room_members enable row level security;
alter table public.messages enable row level security;
alter table public.connections enable row level security;
alter table public.wallet_links enable row level security;
alter table public.ledger_accounts enable row level security;
alter table public.ledger_entries enable row level security;
alter table public.ledger_postings enable row level security;

grant select, update on public.profiles to authenticated;
grant select, update on public.user_private to authenticated;
grant select, insert, update on public.rooms to authenticated;
grant select, insert, update, delete on public.room_members to authenticated;
grant select, insert, update on public.messages to authenticated;
grant select, insert, update on public.connections to authenticated;
grant select, insert, delete on public.wallet_links to authenticated;
grant select on public.ledger_accounts, public.ledger_entries, public.ledger_postings to authenticated;

create policy "authenticated profiles are discoverable"
on public.profiles for select to authenticated
using (onboarding_completed_at is not null or id = (select auth.uid()));

create policy "users update own profile"
on public.profiles for update to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

create policy "users read own private record"
on public.user_private for select to authenticated
using (id = (select auth.uid()));

create policy "users update own private record"
on public.user_private for update to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

create policy "authenticated users read rooms"
on public.rooms for select to authenticated
using (status <> 'archived');

create policy "users create own rooms"
on public.rooms for insert to authenticated
with check (created_by = (select auth.uid()));

create policy "room creators update rooms"
on public.rooms for update to authenticated
using (created_by = (select auth.uid()))
with check (created_by = (select auth.uid()));

create policy "authenticated users read room membership"
on public.room_members for select to authenticated
using (true);

create policy "users join as themselves"
on public.room_members for insert to authenticated
with check (user_id = (select auth.uid()));

create policy "users update own membership"
on public.room_members for update to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

create policy "users leave rooms"
on public.room_members for delete to authenticated
using (user_id = (select auth.uid()));

create policy "room members read messages"
on public.messages for select to authenticated
using (
  exists (
    select 1 from public.room_members rm
    where rm.room_id = messages.room_id
      and rm.user_id = (select auth.uid())
      and rm.left_at is null
  )
);

create policy "room members send messages"
on public.messages for insert to authenticated
with check (
  sender_id = (select auth.uid())
  and exists (
    select 1 from public.room_members rm
    where rm.room_id = messages.room_id
      and rm.user_id = (select auth.uid())
      and rm.left_at is null
  )
);

create policy "authors edit messages"
on public.messages for update to authenticated
using (sender_id = (select auth.uid()))
with check (sender_id = (select auth.uid()));

create policy "participants read connections"
on public.connections for select to authenticated
using (
  requester_id = (select auth.uid())
  or addressee_id = (select auth.uid())
);

create policy "users request connections"
on public.connections for insert to authenticated
with check (requester_id = (select auth.uid()));

create policy "participants update connections"
on public.connections for update to authenticated
using (
  requester_id = (select auth.uid())
  or addressee_id = (select auth.uid())
)
with check (
  requester_id = (select auth.uid())
  or addressee_id = (select auth.uid())
);

create policy "users manage own wallet links"
on public.wallet_links for select to authenticated
using (user_id = (select auth.uid()));
create policy "users add own wallet links"
on public.wallet_links for insert to authenticated
with check (user_id = (select auth.uid()));
create policy "users remove own wallet links"
on public.wallet_links for delete to authenticated
using (user_id = (select auth.uid()));

create policy "users read own ledger accounts"
on public.ledger_accounts for select to authenticated
using (owner_user_id = (select auth.uid()));

create policy "users read entries touching own accounts"
on public.ledger_entries for select to authenticated
using (
  exists (
    select 1
    from public.ledger_postings lp
    join public.ledger_accounts la on la.id = lp.account_id
    where lp.entry_id = ledger_entries.id
      and la.owner_user_id = (select auth.uid())
  )
);

create policy "users read own postings"
on public.ledger_postings for select to authenticated
using (
  exists (
    select 1
    from public.ledger_accounts la
    where la.id = ledger_postings.account_id
      and la.owner_user_id = (select auth.uid())
  )
);

commit;
