begin;

alter table public.room_members
  add column if not exists entry_state text not null default 'active',
  add column if not exists ejected_at timestamptz;

alter table public.room_members
  add constraint room_members_entry_state_known
    check (entry_state in ('active', 'ejected')),
  add constraint room_members_ejection_consistent
    check (
      (entry_state = 'active' and ejected_at is null)
      or
      (entry_state = 'ejected' and ejected_at is not null and left_at is not null)
    );

-- Membership lifecycle is now server-owned. A browser may read only its own
-- membership record and may not reactivate, update, or delete membership.
revoke insert, update, delete on table public.room_members from authenticated;

drop policy if exists "users join as themselves" on public.room_members;
drop policy if exists "users update own membership" on public.room_members;
drop policy if exists "users leave rooms" on public.room_members;
drop policy if exists "authenticated users read room membership" on public.room_members;

create policy "users read own room membership"
on public.room_members for select to authenticated
using (user_id = (select auth.uid()));

grant select, insert, update, delete on table public.room_members to service_role;

create table public.room_member_moderation_actions (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete restrict,
  target_user_id uuid not null references public.profiles(id) on delete restrict,
  actor_id uuid not null references public.profiles(id) on delete restrict,
  action text not null,
  reason text not null,
  created_at timestamptz not null default now(),
  constraint room_member_moderation_action_known check (action in ('host_eject')),
  constraint room_member_moderation_reason_length
    check (char_length(reason) between 3 and 500),
  constraint room_member_moderation_no_self check (target_user_id <> actor_id)
);

create index room_member_moderation_actions_room_created_idx
on public.room_member_moderation_actions(room_id, created_at desc);

create index room_member_moderation_actions_target_created_idx
on public.room_member_moderation_actions(target_user_id, created_at desc);

alter table public.room_member_moderation_actions enable row level security;
revoke all on table public.room_member_moderation_actions
  from public, anon, authenticated;
grant select, insert on table public.room_member_moderation_actions to service_role;

create or replace function public.host_eject_room_member(
  p_room_id uuid,
  p_target_user_id uuid,
  p_actor_id uuid,
  p_reason text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  action_id bigint;
  member_state text;
begin
  if p_actor_id = p_target_user_id then
    raise exception 'Room host cannot eject self';
  end if;

  if p_reason is null
     or char_length(btrim(p_reason)) < 3
     or char_length(btrim(p_reason)) > 500 then
    raise exception 'An ejection reason between 3 and 500 characters is required';
  end if;

  perform 1
  from public.rooms r
  where r.id = p_room_id
    and r.created_by = p_actor_id
    and r.status = 'open';

  if not found then
    raise exception 'Actor is not the active room host';
  end if;

  select rm.entry_state
    into member_state
  from public.room_members rm
  where rm.room_id = p_room_id
    and rm.user_id = p_target_user_id
  for update;

  if member_state is null then
    raise exception 'Target is not a room member';
  end if;

  if member_state = 'ejected' then
    select a.id
      into action_id
    from public.room_member_moderation_actions a
    where a.room_id = p_room_id
      and a.target_user_id = p_target_user_id
      and a.action = 'host_eject'
    order by a.created_at desc
    limit 1;

    if action_id is not null then
      return action_id;
    end if;
  else
    update public.room_members
    set
      entry_state = 'ejected',
      ejected_at = now(),
      left_at = now()
    where room_id = p_room_id
      and user_id = p_target_user_id;
  end if;

  insert into public.room_member_moderation_actions(
    room_id,
    target_user_id,
    actor_id,
    action,
    reason
  ) values (
    p_room_id,
    p_target_user_id,
    p_actor_id,
    'host_eject',
    btrim(p_reason)
  )
  returning id into action_id;

  return action_id;
end;
$$;

revoke execute on function public.host_eject_room_member(uuid, uuid, uuid, text)
  from public, anon, authenticated;
grant execute on function public.host_eject_room_member(uuid, uuid, uuid, text)
  to service_role;

commit;
