begin;

create or replace function public.profile_is_discoverable(target_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $
  select exists (
    select 1
    from public.profiles p
    join public.user_access ua on ua.id = p.id
    where p.id = target_user_id
      and p.onboarding_completed_at is not null
      and ua.account_status = 'active'::public.account_status
  );
$;

revoke execute on function public.profile_is_discoverable(uuid) from public, anon;
grant execute on function public.profile_is_discoverable(uuid) to authenticated;

drop policy if exists "active profiles are discoverable" on public.profiles;
create policy "active profiles are discoverable"
on public.profiles for select to authenticated
using (
  (select public.current_user_is_active())
  and (
    id = (select auth.uid())
    or (select public.profile_is_discoverable(id))
  )
);

create type public.resonance_reason_code as enum (
  'same_intent',
  'complementary_intent',
  'shared_interests',
  'compatible_intent'
);

create type public.resonance_outcome_kind as enum (
  'profile_opened',
  'room_entered',
  'connection_requested',
  'connection_accepted',
  'blocked',
  'reported',
  'repeat_interaction'
);

create table public.discovery_impression_batches (
  id uuid primary key default gen_random_uuid(),
  viewer_id uuid not null references public.profiles(id) on delete cascade,
  algorithm_version text not null default 'resonance_v1',
  surface text not null default 'discover_people',
  created_at timestamptz not null default now(),
  constraint discovery_batch_algorithm check (algorithm_version = 'resonance_v1'),
  constraint discovery_batch_surface check (surface = 'discover_people')
);

create table public.discovery_impressions (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references public.discovery_impression_batches(id) on delete cascade,
  viewer_id uuid not null references public.profiles(id) on delete cascade,
  candidate_id uuid not null references public.profiles(id) on delete cascade,
  rank smallint not null,
  score smallint not null,
  reason_code public.resonance_reason_code not null,
  created_at timestamptz not null default now(),
  constraint discovery_impression_rank check (rank between 1 and 12),
  constraint discovery_impression_score check (score between 0 and 100),
  constraint discovery_impression_not_self check (viewer_id <> candidate_id),
  unique (batch_id, candidate_id)
);

create table public.discovery_outcomes (
  id bigint generated by default as identity primary key,
  impression_id bigint not null references public.discovery_impressions(id) on delete cascade,
  viewer_id uuid not null references public.profiles(id) on delete cascade,
  outcome_kind public.resonance_outcome_kind not null,
  room_id uuid references public.rooms(id) on delete set null,
  occurred_at timestamptz not null default now()
);

create index discovery_batches_viewer_created_idx
  on public.discovery_impression_batches(viewer_id, created_at desc);
create index discovery_impressions_viewer_created_idx
  on public.discovery_impressions(viewer_id, created_at desc);
create index discovery_impressions_candidate_created_idx
  on public.discovery_impressions(candidate_id, created_at desc);
create index discovery_outcomes_viewer_created_idx
  on public.discovery_outcomes(viewer_id, occurred_at desc);
create unique index discovery_outcomes_idempotent_idx
  on public.discovery_outcomes(
    impression_id,
    outcome_kind,
    coalesce(room_id, '00000000-0000-0000-0000-000000000000'::uuid)
  );

alter table public.discovery_impression_batches enable row level security;
alter table public.discovery_impressions enable row level security;
alter table public.discovery_outcomes enable row level security;

revoke all on public.discovery_impression_batches from anon, authenticated;
revoke all on public.discovery_impressions from anon, authenticated;
revoke all on public.discovery_outcomes from anon, authenticated;

create or replace function public.record_resonance_impression_batch(
  p_candidate_ids uuid[],
  p_scores smallint[],
  p_reason_codes text[]
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  viewer uuid := auth.uid();
  batch_id uuid;
  candidate_count integer := cardinality(p_candidate_ids);
begin
  if viewer is null then
    raise exception 'Authentication required';
  end if;

  if not public.current_user_can_enter() then
    raise exception 'Full app access required';
  end if;

  if candidate_count is null or candidate_count < 1 or candidate_count > 12 then
    raise exception 'Impression batch must contain between 1 and 12 candidates';
  end if;

  if cardinality(p_scores) is distinct from candidate_count
    or cardinality(p_reason_codes) is distinct from candidate_count then
    raise exception 'Impression arrays must have equal length';
  end if;

  if exists (
    select 1
    from unnest(p_candidate_ids) as candidates(candidate_id)
    group by candidate_id
    having count(*) > 1
  ) then
    raise exception 'Impression candidates must be unique';
  end if;

  if viewer = any(p_candidate_ids) then
    raise exception 'Viewer cannot be their own discovery candidate';
  end if;

  if exists (
    select 1
    from unnest(p_scores) as scores(score)
    where score < 0 or score > 100
  ) then
    raise exception 'Resonance score must be between 0 and 100';
  end if;

  if exists (
    select 1
    from unnest(p_reason_codes) as reasons(reason_code)
    where reason_code not in (
      'same_intent',
      'complementary_intent',
      'shared_interests',
      'compatible_intent'
    )
  ) then
    raise exception 'Unknown resonance reason code';
  end if;

  if exists (
    select 1
    from unnest(p_candidate_ids) as candidates(candidate_id)
    where not public.profile_is_discoverable(candidate_id)
  ) then
    raise exception 'All discovery candidates must be active, onboarded profiles';
  end if;

  insert into public.discovery_impression_batches(viewer_id)
  values (viewer)
  returning id into batch_id;

  insert into public.discovery_impressions(
    batch_id,
    viewer_id,
    candidate_id,
    rank,
    score,
    reason_code
  )
  select
    batch_id,
    viewer,
    candidate_id,
    rank_position::smallint,
    p_scores[rank_position::integer]::smallint,
    p_reason_codes[rank_position::integer]::public.resonance_reason_code
  from unnest(p_candidate_ids) with ordinality as ranked(candidate_id, rank_position);

  return batch_id;
end;
$$;

create or replace function public.record_resonance_outcome(
  p_batch_id uuid,
  p_candidate_id uuid,
  p_outcome_kind text,
  p_room_id uuid default null
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  viewer uuid := auth.uid();
  stored_viewer uuid;
  impression_id bigint;
  parsed_kind public.resonance_outcome_kind;
begin
  if viewer is null then
    raise exception 'Authentication required';
  end if;

  begin
    parsed_kind := p_outcome_kind::public.resonance_outcome_kind;
  exception
    when invalid_text_representation then
      raise exception 'Unknown resonance outcome kind';
  end;

  select di.viewer_id, di.id
  into stored_viewer, impression_id
  from public.discovery_impressions di
  where di.batch_id = p_batch_id
    and di.candidate_id = p_candidate_id;

  if stored_viewer is null or stored_viewer <> viewer then
    raise exception 'Impression is not owned by the authenticated viewer';
  end if;

  if parsed_kind = 'room_entered'::public.resonance_outcome_kind then
    if p_room_id is null then
      raise exception 'room_entered outcome requires a room id';
    end if;

    if not exists (
      select 1
      from public.room_members rm
      where rm.room_id = p_room_id
        and rm.user_id = viewer
    ) then
      raise exception 'room_entered outcome requires room membership';
    end if;
  end if;

  insert into public.discovery_outcomes(
    impression_id,
    viewer_id,
    outcome_kind,
    room_id
  )
  values (
    impression_id,
    viewer,
    parsed_kind,
    p_room_id
  )
  on conflict do nothing;

  return true;
end;
$$;

revoke execute on function public.record_resonance_impression_batch(uuid[], smallint[], text[])
  from public, anon;
revoke execute on function public.record_resonance_outcome(uuid, uuid, text, uuid)
  from public, anon;

grant execute on function public.record_resonance_impression_batch(uuid[], smallint[], text[])
  to authenticated;
grant execute on function public.record_resonance_outcome(uuid, uuid, text, uuid)
  to authenticated;

commit;
