begin;

create table public.room_moderation_actions (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete restrict,
  actor_id uuid not null references public.user_access(id) on delete restrict,
  actor_role public.app_role not null,
  action text not null,
  reason text not null,
  created_at timestamptz not null default now(),
  constraint room_moderation_action_known check (action in ('moderation_close')),
  constraint room_moderation_reason_length check (char_length(reason) between 3 and 500),
  constraint room_moderation_actor_role check (actor_role in ('moderator', 'admin'))
);

create index room_moderation_actions_room_created_idx
  on public.room_moderation_actions(room_id, created_at desc);
create index room_moderation_actions_actor_created_idx
  on public.room_moderation_actions(actor_id, created_at desc);

alter table public.room_moderation_actions enable row level security;
revoke all on public.room_moderation_actions from public, anon, authenticated;

create or replace function public.moderation_close_live_room(
  p_room_id uuid,
  p_actor_id uuid,
  p_actor_role public.app_role,
  p_reason text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  action_id bigint;
  stored_role public.app_role;
begin
  if p_reason is null or char_length(btrim(p_reason)) < 3 or char_length(btrim(p_reason)) > 500 then
    raise exception 'A moderation reason between 3 and 500 characters is required';
  end if;

  select ua.role
    into stored_role
  from public.user_access ua
  where ua.id = p_actor_id
    and ua.account_status = 'active'
    and ua.role in ('moderator', 'admin');

  if stored_role is null or stored_role <> p_actor_role then
    raise exception 'Actor is not authorized for live-room moderation';
  end if;

  update public.rooms
  set status = 'closed'
  where id = p_room_id
    and status <> 'archived';

  if not found then
    raise exception 'Live room is unavailable for moderation closure';
  end if;

  insert into public.room_moderation_actions(
    room_id,
    actor_id,
    actor_role,
    action,
    reason
  ) values (
    p_room_id,
    p_actor_id,
    stored_role,
    'moderation_close',
    btrim(p_reason)
  )
  returning id into action_id;

  return action_id;
end;
$$;

revoke execute on function public.moderation_close_live_room(uuid, uuid, public.app_role, text)
  from public, anon, authenticated;
grant execute on function public.moderation_close_live_room(uuid, uuid, public.app_role, text)
  to service_role;

commit;
